- wechat_hook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=609a7fae-cba3-4eae-afe4-7159e3fcfada
  repo: redis
  config:
  - event: push
    type: text
    content: "hello"
  - event: default
    type: text
    content: "hello"
